### ISSUE TITLE
all.json master schema that automatically selects correct (sub)schema from `kind` and `apiVersion`

### ISSUE THREAD

**Issue by kevinvalk** [fluxcd-community/flux2-schemas#23]
The https://github.com/yannh/kubernetes-json-schema repository contains special `all.json` files that can be used to automatically match a file to the correct JSON schema based on the `kind` and `version` (and others) values. It uses the https://json-schema.org/understanding-json-schema/reference/combining specs.

For example https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.27.1-standalone-strict/all.json uses `oneOf` and the usage of `enum` inside the schema https://github.com/yannh/kubernetes-json-schema/blob/master/v1.23.4/mutatingwebhookconfiguration-admissionregistration-v1.json#L4C1-L23C7 to automatically select the correct schema based on kind and apiVersion.

It would be awesome to also have a `all.json` file for flux2 so you can simply say, all files in this directory should follow from this schema!

**Comment by JJGadgets** [comment]
I'll look into this when I have some free time, if you don't see any activity (PR or commits or activity on this issue) on it yet, feel free to beat me to it with a PR of your own haha.

**Comment by budimanjojo** [comment]
I feel like this is more suitable to be done from the source (https://github.com/fluxcd/pkg/blob/main/actions/crdjsonschema/openapi2jsonschema.py)

**Comment by kevinvalk** [comment]
In theory this is done if PR https://github.com/fluxcd/pkg/pull/744 is merged and this repo is updated.

**Comment by kevinvalk** [comment]
I guess we can close this as done? With the next release of Flux everything should "resolve" automatically and have the new all.json schema included in this repository.

**Comment by budimanjojo** [comment]
Yeah I'll close this. Thanks @kevinvalk for the work!
